project:
  type: website
  output-dir: docs
  
website:
  title: "Frank Shinost"
  navbar:
    left:
      - href: https://github.com/FShinost/Shi_websitefun.git
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/YOURUSERNAME/YOURREPO
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Frank Shinost"

format:
  html:
    theme: cerulean
    toc: true

editor: source

